# -*- coding: utf-8 -*-
"""Day2 Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eOgyKoeP9ogx5H4-Kc_zdwtF5n8cJlr3
"""

!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python==0.2.28 --force-reinstall --no-cache-dir -q

!pip install huggingface_hub==0.35.3

#Libraries for downloading and loading the llm
from huggingface_hub import hf_hub_download
from llama_cpp import Llama

model_path = hf_hub_download(
    repo_id=model_name_or_path,
    filename=model_basename
)

llm = Llama(
    model_path=model_path,
    n_ctx=15000,
    n_gpu_layers=38,
    n_batch=512
)

def Prompt(query,max_tokens=512,temperature=0,top_p=0.5,top_k=20):
    model_output = llm(
      prompt=query,
      max_tokens=max_tokens,
      temperature=temperature,
      top_p=top_p,
      top_k=top_k
    )

    return model_output['choices'][0]['text']

"""# Client Email Draft"""

query = """Act as an expert analyst to summarize below quartely report. Provide a role-based prompt, a concise 150-word summary, a table of key metrics, and a risk/opportunity section. Ensure the content is fact-based, avoids hallucination, and cites sources if needed. \n\nOutput Format:\nSummary (150 words): [Your summary here]\n\nMetrics Table:\n| Metric | Value | Unit |\n|---|---|---|\n| Metric 1 | Value 1 | Unit 1 |\n| Metric 2 | Value 2 | Unit 2 |\n\nRisk/Opportunity Section:\n[Your risk/opportunity analysis here]\n\nGuardrails:\n- Fact-based only; no hallucination\n- Cite source if needed"""

response = Prompt(query)
print(response)

"""#Executive Sumary Generator"""

query = """Scenario: Draft a professional email to a client summarizing project progress, milestones, and requesting feedback.\nRequirements: Formal tone; placeholders for client name, project name, deadline; include action items.\nExpected Output Format: Email text with subject line + bullet points for action items\nGuardrails: Maintain professional tone; avoid sensitive data.\n\nGenerate the client email draft based on these details."""

response = Prompt(query)
print(response)

"""#Policy Compliance Checker"""

query = """ Act as expect HR to figure oit the missing compliance clause, ambiguous language, and suggest imporvement

Generate output JSON with below format:
JSON:{ ""issues":[],
"Severity":[]
"recommendations":[]}

Do not inver compliance rules; base base suggesion on provided context

context:
1. Essential Core Policies
These foundational policies are critical for nearly every organization regardless of size:
At-Will Employment Statement: Clarifies that the relationship can be terminated at any time by either party.
Equal Employment Opportunity (EEO): Formally commits to non-discrimination based on protected classes like race, gender, and religion.
Anti-Harassment & Anti-Bullying: Defines prohibited behavior and provides a clear process for reporting incidents without retaliation.
Code of Conduct: Outlines behavioral expectations, ethical standards, and professional standards for the workplace.
Confidentiality & Data Privacy: Protects sensitive company information and employee personal data, often updated for 2026 privacy regulations.
2. Operational & Workplace Policies
These govern daily business activities and the work environment:
Remote & Hybrid Work: Sets expectations for hours, communication protocols, and company-provided equipment.
Timekeeping & Pay: Detailed procedures for recording hours, overtime eligibility, and payday schedules.
Leave & Absence: Covers vacation (PTO), sick leave, and legally mandated leaves like FMLA or bereavement.
Performance Management: Explains how employees are evaluated, promoted, and the steps for disciplinary actions.
IT & Social Media: Guidelines for using company devices, internet access, and representing the brand online.
3. Emerging Trends for 2026
Recent legislative shifts have made the following policies a high priority:
AI Governance: Discloses if AI tools are used for recruitment, performance reviews, or layoffs, as required by new laws in states like Colorado and Illinois.
Pay Transparency: Requires employers to disclose good-faith salary ranges in job postings and for internal promotions.
Workplace Violence Prevention: Formal plans for safety and reporting, including new requirements for emergency contact designations.
Lactation Accommodations: Specifically updated policies to comply with expanded federal and state laws regarding paid breaks for nursing mothers.
4. Policy Administration Best Practices
Annual Review: Conduct an annual audit of the employee handbook to ensure it matches current federal and state labor laws.
Acknow ledgment Form: Always require a signed acknowledgment from employees whenever policies are issued or updated.
Manager Training: Ensure supervisors are trained on how to apply policies consistently to avoid discrimination claims.
"""


response = Prompt(query)
print(response)

"""#Meeting Minutes Summarizer"""

query = """ Act as project manager and help to sumarries the below provided content with decision, action iteam with owners and deadline

Structure markdown; inclide confidence score for each item

Markdown: ## Decisions, ## Action Items

Avoid adding items not in transcript

content:
sing the sample agenda, the following is a sample transcript of a meeting that has 19 members and a regular member is serving as chair.

Meeting of CTAS County Commission-Transcript of Dialogue

Chairman Wormsley (at the proper time and place, after taking the chair and striking the gavel on the table): This meeting of the CTAS County Commission will come to order. Clerk please call the role. (Ensure that a majority of the members are present.)

Chairman Wormsley: Each of you has received the agenda. I will entertain a motion that the agenda be approved.

Commissioner Brown: So moved.

Commissioner Hobbs: Seconded

Chairman Wormsley: It has been moved and seconded that the agenda be approved as received by the members. All those in favor signify by saying "Aye"?...Opposed by saying "No"?...The agenda is approved. You have received a copy of the minutes of the last meeting. Are there any corrections or additions to the meeting?

Commissioner McCroskey: Mister Chairman, my name has been omitted from the Special Committee on Indigent Care.

Chairman Wormsley: Thank you. If there are no objections, the minutes will be corrected to include the name of Commissioner McCroskey. Will the clerk please make this correction. Any further corrections? Seeing none, without objection the minutes will stand approved as read. (This is sort of a short cut way that is commonly used for approval of minutes and/or the agenda rather than requiring a motion and second.)

Chairman Wormsley: Commissioner Adkins, the first item on the agenda is yours.

Commissioner Adkins: Mister Chairman, I would like to make a motion to approve the resolution taking money from the Data Processing Reserve Account in the County Clerk's office and moving it to the equipment line to purchase a laptop computer.

Commissioner Carmical: I second the motion.

Chairman Wormsley: This resolution has a motion and second. Will the clerk please take the vote.

Chairman Wormsley: The resolution passes. We will now take up old business. At our last meeting, Commissioner McKee, your motion to sell property near the airport was deferred to this meeting. You are recognized.

Commissioner McKee: I move to withdraw that motion.

Chairman Wormsley: Commissioner McKee has moved to withdraw his motion to sell property near the airport. Seeing no objection, this motion is withdrawn. The next item on the agenda is Commissioner Rodgers'.

Commissioner Rodgers: I move adopton of the resolution previously provided to each of you to increase the state match local litigation tax in circuit, chancery, and criminal courts to the maximum amounts permissible. This resolution calls for the increases to go to the general fund.

Chairman Wormsley: Commissioner Duckett

Commissioner Duckett: The sheriff is opposed to this increase.

Chairman Wormsley: Commissioner, you are out of order because this motion has not been seconded as needed before the floor is open for discussion or debate. Discussion will begin after we have a second. Is there a second?

Commissioner Reinhart: For purposes of discussion, I second the motion.

Chairman Wormsley: Commissioner Rodgers is recognized.

Commissioner Rodgers: (Speaks about the data on collections, handing out all sorts of numerical figures regarding the litigation tax, and the county's need for additional revenue.)

Chairman Wormsley: Commissioner Duckett

Commissioner Duckett: I move an amendment to the motion to require 25 percent of the proceeds from the increase in the tax on criminal cases go to fund the sheriff's department.

Chairman Wormsley: Commissioner Malone

Commissioner Malone: I second the amendment.

Chairman Wormsley: A motion has been made and seconded to amend the motion to increase the state match local litigation taxes to the maximum amounts to require 25 percent of the proceeds from the increase in the tax on criminal cases in courts of record going to fund the sheriff's department. Any discussion? Will all those in favor please raise your hand? All those opposed please raise your hand. The amendment carries 17-2. We are now on the motion as amended. Any further discussion?

Commissioner Headrick: Does this require a two-thirds vote?

Chairman Wormsley: Will the county attorney answer that question?

County Attorney Fults: Since these are only courts of record, a majority vote will pass it. The two-thirds requirement is for the general sessions taxes.

Chairman Wormsley: Other questions or discussion? Commissioner Adams.

Commissioner Adams: Move for a roll call vote.

Commissioner Crenshaw: Second

Chairman Wormsley: The motion has been made and seconded that the state match local litigation taxes be increased to the maximum amounts allowed by law with 25 percent of the proceeds from the increase in the tax on criminal cases in courts of record going to fund the sheriff's department. Will all those in favor please vote as the clerk calls your name, those in favor vote "aye," those against vote "no." Nine votes for, nine votes against, one not voting. The increase fails. We are now on new business. Commissioner Adkins, the first item on the agenda is yours.

Commissioner Adkins: Each of you has previously received a copy of a resolution to increase the wheel tax by $10 to make up the state cut in education funding. I move adoption of this resolution.

Chairman Wormsley: Commissioner Thompson

Commissioner Thompson: I second.

Chairman Wormsley: It has been properly moved and seconded that a resolution increasing the wheel tax by $10 to make up the state cut in education funding be passed. Any discussion? (At this point numerous county commissioners speak for and against increasing the wheel tax and making up the education cuts. This is the first time this resolution is under consideration.) Commissioner Hayes is recognized.

Commissioner Hayes: I move previous question.

Commisioner Crenshaw: Second.

Chairman Wormsley: Previous question has been moved and seconded. As you know, a motion for previous question, if passed by a two-thirds vote, will cut off further debate and require us to vote yes or no on the resolution before us. You should vote for this motion if you wish to cut off further debate of the wheel tax increase at this point. Will all those in favor of previous question please raise your hand? Will all those against please raise your hand? The vote is 17-2. Previous question passes. We are now on the motion to increase the wheel tax by $10 to make up the state cut in education funding. Will all those in favor please raise your hand? Will all those against please raise your hand? The vote is 17-2. This increase passes on first passage. Is there any other new business? Since no member is seeking recognition, are there announcements? Commissioner Hailey.

Commissioner Hailey: There will be a meeting of the Budget Committee to look at solid waste funding recommendations on Tuesday, July 16 at noon here in this room.

Chairman Wormsley: Any other announcements? The next meeting of this body will be Monday, August 19 at 7 p.m., here in this room. Commissioner Carmical.

Commissioner Carmical: There will be a chili supper at County Elementary School on August 16 at 6:30 p.m. Everyone is invited.

Chairman Wormsley: Commissioner Austin.

Commissioner Austin: Move adjournment.

Commissioner Garland: Second.

Chairman Wormsley: Without objection, the meeting will stand adjourned
"""


response = Prompt(query)
print(response)

"""#Market Analysis Brief"""

query = """ Act as market analyst to bri the multiple news articals and infternal reports

inlcude SWOT analysis; highlight top 3 treands and provide citations

output formate: JSON and narrative summary with citations for each trend

No fabricated data ensure all trend are supported by sources """


response = Prompt(query)
print(response)
